name: CopyToOpenManual

on:
  push:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  DST_DIRNAME: "${{ github.event.repository.name }}"
  SRC_FILEPATH: 'README.md'
  SRC_DIR: './current'
  DST_DIR: './openman'
  SRC_REPO_NAME: "${{ github.event.repository.name }}"
  DST_REPO: 'SatorImaging/OpenManual'
  DST_BRANCH: 'master'
  PULLREQ_TITLE: "GitHub Actions"
  PULLREQ_MESSAGE: "${{ github.workflow }}"


jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          path: "${{ env.SRC_DIR }}"

      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          repository: "${{ env.DST_REPO }}"
          path: "${{ env.DST_DIR }}"

      - name: Update Env
        run: echo "PR_BRANCH=${SRC_REPO_NAME}---$(date +'%Y-%m-%d--%H-%M-%S')" >> $GITHUB_ENV

      - name: Commit & PR
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "devnull@inter.net"
          git config --global url."https://${{ secrets.DST_REPO_TKN}}@github.com/".insteadOf "https://github.com/"

          cd "${DST_DIR}"
          git checkout -b "${PR_BRANCH}"

          mkdir "${DST_DIRNAME}"
          cp -f "../${SRC_DIR}/${SRC_FILEPATH}" "${DST_DIRNAME}/${SRC_FILEPATH}"

          git add "."
          git commit -am "`date`"
          git push origin HEAD

          curl -X POST \
            -H 'Accept: application/vnd.github.v3+json' \
            'https://${{ secrets.DST_REPO_TKN}}@api.github.com/repos/${DST_REPO}/pulls' \
            -d "{ \"title\":\"${PULLREQ_TITLE}\", \"body\":\"${PULLREQ_MESSAGE}\", \"head\":\"${PR_BRANCH}\", \"base\":\"${DST_BRANCH}\" }"
