name: CopyToOpenManual

on:
  push:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  DIRNAME: 'VSCode-MEL'
  FILENAME: 'README.md'
  SRC_DIR: './current'
  DST_DIR: './openman'
  SRC_REPO_NAME: "${{ github.event.repository.name }}"
  DST_REPO: 'SatorImaging/OpenManual'
  DST_BRANCH: 'master'
  PULLREQ_TITLE: "CopyToOpenManual"
  PULLREQ_MESSAGE: "CopyToOpenManual"


jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: "${{ env.SRC_DIR }}"
      - uses: actions/checkout@v3
        with:
          repository: "${{ env.DST_REPO }}"
          path: "${{ env.DST_DIR }}"

      - name: Create pull-request.
        run: |
          mkdir "${DST_DIR}/${DIRNAME}"
          copy "${SRC_DIR}/${FILENAME}" "${DST_DIR}/${DIRNAME}/${FILENAME}"
          ls .
          cd "${DST_DIR}"
          
          git branch -b "${SRC_REPO_NAME}"
          git add "."
          git commit -am `date +%s`
          git push origin HEAD

          curl -X POST \
            -H 'Accept: application/vnd.github.v3+json' \
            https://api.github.com/repos/${DST_REPO}/pulls \
            -d "{ \"title\":\"${PULLREQ_TITLE}\", \"body\":\"${PULLREQ_MESSAGE}\", \"head\":\"${SRC_REPO_NAME}\", \"base\":\"${DST_BRANCH}\" }'
