name: OpenManual

on:
  push:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  DIRNAME: 'VSCode-MEL'
  FILENAME: 'README.md'
  SRC_DIR: './current'
  DST_DIR: './openman'
  SRC_REPO: "${{ github.event.repository.name }}"
  DST_REPO: 'SatorImaging/OpenManual'
  DST_BRANCH: 'master'
  PULLREQ_TITLE: 'bot: Copy to OpenManual'
  PULLREQ_MESSAGE: 'bot: Copy to OpenManual'


jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
      - uses: actions/checkout@v3
        with:
          path: "${SRC_DIR}"

      # Runs a single command using the runners shell
      - name: Checkout OpenManual
      - uses: actions/checkout@v3
        with:
          repository: "${DST_REPO}"
          path: "${DST_DIR}"

      # Runs a set of commands using the runners shell
      - name: Create pull-request.
        run: |
          mkdir "${DST_DIR}/${DIRNAME}"
          copy "${SRC_DIR}/${FILENAME}" "${DST_DIR}/${DIRNAME}/${FILENAME}"
          cd "${DST_DIR}"
          
          git branch -b "${SRC_REPO}"
          git add "."
          git commit -am `date +%s`
          git push origin HEAD

          curl -X POST \
            -H 'Accept: application/vnd.github.v3+json'
            'https://api.github.com/repos/${DST_REPO}/pulls'
            -d "{ \"title\":\"${PULLREQ_TITLE}\", \"body\":\"${PULLREQ_MESSAGE}\", \"head\":\"${SRC_REPO}\", \"base\":\"${DST_BRANCH}\" }'
            
