name: Deploy2OM

on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: sator-imaging/Deploy-to-Another-Repository@main
        with:
          target-filepath: 'README.md'
          output-repo: 'SatorImaging/OpenManual'
          output-branch: 'master'
          git-token: ${{ secrets.DST_REPO_TKN }}
