name: Deploy2OM

on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: sator-imaging/Copy-to-Another-Repository@v1
        with:
          target-filepath: 'README.md'
          output-repo: 'SatorImaging/OpenManual'
          output-branch: 'master'
          git-token: ${{ secrets.DST_REPO_TKN }}
          git-email: '16752340+sator-imaging@users.noreply.github.com'
