name: Deploy2OM

on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


env:
  DST_BRANCH: 'master'
  DST_REPO: 'SatorImaging/OpenManual'
  DST_DIRNAME: "${{ github.event.repository.name }}"
  SRC_REPO_NAME: "${{ github.event.repository.name }}"
  SRC_FILEPATH: 'README.md'
  TMP_SRCDIR: './source'
  TMP_DSTDIR: './dest'
  PULLREQ_TITLE: "GitHub Actions: ${{ github.workflow }}"
  PULLREQ_MESSAGE: ""


jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          path: "${{ env.TMP_SRCDIR }}"

      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          repository: "${{ env.DST_REPO }}"
          path: "${{ env.TMP_DSTDIR }}"

      - uses: sator-imaging/Deploy-to-Another-Repository@main
        with:
          GITHUB_TOKEN: ${{ secrets.DST_REPO_TKN }}
          target-filepath: 'README.md'
          output-repo: 'SatorImaging/OpenManual'
          output-branch: 'master'
          git-token: ${{ secrets.DST_REPO_TKN }}
